# ZingyTrader - open source client for Stellar Decentralized Exchange <zingypay.com>

ACCOUNTS = ["GAZ237H33DS6AMCZMPP76DQ3W5WGUVWWBQYLKSO26YFI5JQJOKXEJW2M"]
SIGNING_KEY = "GAEESZVR52HUAHPOJZYWMWS7TYLSPS46IAK3ZDT7HTFBULDVOYUNEWCC"
FEDERATION_SERVER="https://federation.zingypay.com/federation"
NETWORK_PASSPHRASE='Public Global Stellar Network ; September 2015'

TRANSFER_SERVER_SEP0024 = "https://zingytrader.zingypay.com/sep24"
WEB_AUTH_ENDPOINT = "https://zingytrader.zingypay.com/auth"
DIRECT_PAYMENT_SERVER = "https://zingytrader.zingypay.com/sep31"
KYC_SERVER = "https://zingytrader.zingypay.com/kyc"
QUOTE_SERVER = "https://zingytrader.zingypay.com/sep38"


# Add support for CNB
[[CURRENCIES]]
code = "ÇNB"
issuer = "GAEESZVR52HUAHPOJZYWMWS7TYLSPS46IAK3ZDT7HTFBULDVOYUNEWCC"
status = "live"
is_asset_anchored = true
anchor_asset_type = "crypto"
display_decimals=7
fixed_number=10000000
desc = "ÇNB is Cannabis asset created to cater to the ZingyTrader's ecosystem trading hub. Users can readily buy ÇNB and exchange them 1on1000 with OSO. More info in the White Paper."
image="https://res.cloudinary.com/dp7civtid/image/upload/v1695474886/CNB_bvlwjy.png"




DESIRED_BASE_FEE=1000

[DOCUMENTATION]
ORG_URL="https://zingytrader.zingypay.com"
ORG_DBA="ZINGYPAY"
ORG_NAME="ZINGYPAY.COM, LLC"
ORG_OFFICIAL_EMAIL="info@zingypay.com"
ORG_TWITTER="zingypay"
ORG_GITHUB="zingypay"
ORG_LOGO="https://res.cloudinary.com/dp7civtid/image/upload/v1695206970/Zingy-Trader_wexy3k.png"
ORG_DESCRIPTION="Advanced web based trading client for the Stellar network."

[[PRINCIPALS]]
name="Ebarim Godsend"
email="ebarim@zingypay.com"
twitter="@edenlife247"
keybase="aniquel"