# StellarTerm - open source client for Stellar Decentralized Exchange <zingypay.com>

FEDERATION_SERVER="https://zingypay.com/federation/"


DESIRED_BASE_FEE=1000

[DOCUMENTATION]
ORG_URL="https://zingypay.com"
ORG_DBA="StellarTerm"
ORG_NAME="ULTRA STELLAR, LLC"
ORG_OFFICIAL_EMAIL="hi@zingypay.com"
ORG_TWITTER="zingypay"
ORG_GITHUB="zingypay"
ORG_LOGO="https://zingypay.com/favicon-196.png"
ORG_DESCRIPTION="Advanced web based trading client for the Stellar network."

